In [1]:
pip install transformers

     |████████████████████████████████| 660 kB 5.5 MB/s eta 0:00:01
     |████████████████████████████████| 1.1 MB 20.1 MB/s eta 0:00:01
     |████████████████████████████████| 675 kB 36.6 MB/s eta 0:00:01
     |████████████████████████████████| 63 kB 5.5 MB/s  eta 0:00:01
     |████████████████████████████████| 883 kB 32.1 MB/s eta 0:00:01
     |████████████████████████████████| 3.8 MB 39.0 MB/s eta 0:00:01MB 39.0 MB/s eta 0:00:01
     |████████████████████████████████| 82 kB 2.5 MB/s  eta 0:00:01
  Created wheel for sacremoses: filename=sacremoses-0.0.43-py3-none-any.whl size=893258 sha256=36f9a37c215c8596e0630435b9c81a3e894e28ec34ed2f7d0403fa33f06375c3
  Stored in directory: /home/jovyan/.cache/pip/wheels/49/25/98/cdea9c79b2d9a22ccc59540b1784b67f06b633378e97f58da2
Successfully built sacremoses
Note: you may need to restart the kernel to use updated packages.


In [2]:
conda create -n tensorflow_cpu pip python=3.7 -y

Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.2
  latest version: 4.8.3

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /srv/conda/envs/tensorflow_cpu

  added / updated specs:
    - pip
    - python=3.7


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    _libgcc_mutex-0.1          |      conda_forge           3 KB  conda-forge
    _openmp_mutex-4.5          |            0_gnu         435 KB  conda-forge
    ca-certificates-2020.4.5.1 |       hecc5488_0         146 KB  conda-forge
    certifi-2020.4.5.1         |   py37hc8dfbb8_0         151 KB  conda-forge
    ld_impl_linux-64-2.34      |       h53a641e_4         616 KB  conda-forge
    libffi-3.2.1               |    he1b5a44_1007          47 KB  conda-forge
    libgcc-ng-9.2.0            |       h24d8f2e_2         8.2 

In [3]:
pip install --ignore-installed --upgrade tensorflow==2.0

     |████████████████████████████████| 86.3 MB 44.6 MB/s eta 0:00:01     |███████████████████████████████▋| 85.2 MB 44.6 MB/s eta 0:00:01
     |████████████████████████████████| 63 kB 3.6 MB/s  eta 0:00:01
     |████████████████████████████████| 104 kB 31.4 MB/s eta 0:00:01
     |████████████████████████████████| 50 kB 10.5 MB/s eta 0:00:01
     |████████████████████████████████| 1.3 MB 26.3 MB/s eta 0:00:01
     |████████████████████████████████| 3.8 MB 25.8 MB/s eta 0:00:01
     |████████████████████████████████| 57 kB 8.0 MB/s  eta 0:00:01
     |████████████████████████████████| 3.0 MB 26.2 MB/s eta 0:00:01
     |████████████████████████████████| 20.2 MB 27.0 MB/s eta 0:00:01     |███████████████████▋            | 12.4 MB 27.0 MB/s eta 0:00:01     |███████████████████████████████ | 19.6 MB 27.0 MB/s eta 0:00:01
     |████████████████████████████████| 449 kB 28.4 MB/s eta 0:00:01
     |████████████████████████████████| 42 kB 2.4 MB/s  eta 0:00:01
     |██████████████████████████████

In [4]:
pip install torch

     |████████████████████████████████| 752.0 MB 2.4 kB/s  eta 0:00:01    |█▉                              | 44.0 MB 24.6 MB/s eta 0:00:29     |████▉                           | 114.2 MB 32.5 MB/s eta 0:00:20     |█████████                       | 213.8 MB 29.2 MB/s eta 0:00:19     |█████████▍                      | 220.8 MB 29.2 MB/s eta 0:00:19     |████████████▊                   | 298.6 MB 42.4 MB/s eta 0:00:11     |██████████████▌                 | 341.4 MB 68.7 MB/s eta 0:00:06     |████████████████▌               | 387.5 MB 130 kB/s eta 0:46:41     |███████████████████▏            | 450.5 MB 31.3 MB/s eta 0:00:10     |███████████████████▋            | 460.7 MB 31.3 MB/s eta 0:00:10     |█████████████████████▏          | 498.1 MB 38.9 MB/s eta 0:00:07     |███████████████████████▎        | 545.9 MB 45.6 MB/s eta 0:00:05     |███████████████████████▍        | 548.7 MB 45.6 MB/s eta 0:00:05     |███████████████████████████▊    | 651.6 MB 47.9 MB/s eta 0:00:03
     |████████████████

In [5]:
pip install nltk

     |████████████████████████████████| 1.4 MB 5.6 MB/s eta 0:00:01
  Created wheel for nltk: filename=nltk-3.5-py3-none-any.whl size=1434676 sha256=98041d60a5537d9da489dd82da98eddc6aa9fe292b330113defb01aeeac5e46d
  Stored in directory: /home/jovyan/.cache/pip/wheels/de/5e/42/64abaeca668161c3e2cecc24f864a8fc421e3d07a104fc8a51
Successfully built nltk
Note: you may need to restart the kernel to use updated packages.


In [6]:
pip install tensorflow_hub

     |████████████████████████████████| 101 kB 4.4 MB/s ta 0:00:011
Note: you may need to restart the kernel to use updated packages.


In [1]:
# load libraries
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder
import nltk
from nltk.stem import WordNetLemmatizer
from nltk import word_tokenize
import re, string
from collections import Counter
import copy
from pylab import rcParams
from matplotlib import rc


import transformers
import torch
from torch import nn, optim
from torch.utils import data


import tensorflow as tf
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import ModelCheckpoint
import tensorflow_hub as hub

In [2]:
RANDOM_SEED=42
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)

In [3]:
from IPython.display import Image
import random
import math
import string
import os

# Display Keras Model
def show_keras_model(model):
    filename = "".join(random.choices(string.ascii_uppercase, k=10)) + ".png"
    plot_model(model, to_file=filename, show_shapes=True, show_layer_names=True)
    image = Image(filename)
    os.remove(filename)
    return image

# sigmoid
def sigmoid(x):
    return 1.0 / (1 + math.exp(-x))

def tanh(x):
    return math.tanh(x)

In [4]:
with open ('Sentences_50Agree.txt', 'rb') as f:
    text = f.readlines()

with open('Sentences_66Agree.txt', 'rb') as f:
    text2 = f.readlines()

with open('Sentences_75Agree.txt', 'rb') as f:
    text3 = f.readlines()

with open('Sentences_AllAgree.txt', 'rb') as f:
    text4 = f.readlines()

In [5]:
def decodeText(text):
    """
    create two columns dataframe based on text
    
    Input: string/bytes
    
    Output: Tuple(context + label)
    
    """
    # if type of text is bytes, need to decode to string
    if type(text)!='str':
        try:
            text = text.decode("utf-8")
        except:
            text = text.decode("latin-1")
    
    text = text.rstrip()
    ind = text.rfind('@')
    
    return text[:ind], text[ind+1:]

In [6]:
decodeText(text[0])

('According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .',
 'neutral')

In [7]:
# function to load the dataset

from sklearn.utils import Bunch
def load_data(text):
    """
    create context and target based on text
    
    Input: text 
    
    Output: context + label (-1,0,1)
    
    """
    contexts = []
    labels = []
    for t in tqdm(text):
        context, label = decodeText(t)
        if label=='negative':
            label1=0
        elif label=='positive':
            label1=2
        else:
            label1=1
        contexts.append(context)
        labels.append(label1)

    
        
    return pd.DataFrame(zip(contexts, labels), columns = ['contexts','labels'])

In [8]:
data = load_data(text)

100%|██████████| 4846/4846 [00:00<00:00, 239242.89it/s]


In [9]:
# Data preprocessing
from transformers import BertTokenizer

#Load the BERT tokenizer.
print("Loading BERT tokenizer...")
tokenizer=BertTokenizer.from_pretrained("bert-base-uncased", do_lower_case=True)

Loading BERT tokenizer...


In [10]:
sample_text=data.contexts[0]
sample_text

'According to Gran , the company has no plans to move all production to Russia , although that is where the company is growing .'

In [11]:
tokens=tokenizer.tokenize(sample_text)

In [12]:
print(len(tokens))
print(tokens)

25
['according', 'to', 'gran', ',', 'the', 'company', 'has', 'no', 'plans', 'to', 'move', 'all', 'production', 'to', 'russia', ',', 'although', 'that', 'is', 'where', 'the', 'company', 'is', 'growing', '.']


In [13]:
token_ids=tokenizer.convert_tokens_to_ids(tokens)
print(len(token_ids))
print(token_ids)

25
[2429, 2000, 12604, 1010, 1996, 2194, 2038, 2053, 3488, 2000, 2693, 2035, 2537, 2000, 3607, 1010, 2348, 2008, 2003, 2073, 1996, 2194, 2003, 3652, 1012]


In [14]:
encoding = tokenizer.encode_plus(
    sample_text,
    max_length=32,
    add_special_tokens=True,
    pad_to_max_length=True,
    return_attention_mask=True,
    return_token_type_ids=False,
    return_tensor="pt",

)

encoding.keys()
print(encoding["input_ids"])

[101, 2429, 2000, 12604, 1010, 1996, 2194, 2038, 2053, 3488, 2000, 2693, 2035, 2537, 2000, 3607, 1010, 2348, 2008, 2003, 2073, 1996, 2194, 2003, 3652, 1012, 102, 0, 0, 0, 0, 0]


In [15]:
len(data.contexts)

4846

In [16]:
def bert_encode(texts, tokenizer, max_len=512):
    all_tokens = []
    all_masks = []
    all_segments = []
    
    for i in range (0, len(texts)):
        text = tokenizer.tokenize(texts[i])
            
        text = text[:max_len-2]
        input_sequence = ["[CLS]"] + text + ["[SEP]"]
        pad_len = max_len - len(input_sequence)
        
        tokens = tokenizer.convert_tokens_to_ids(input_sequence)
        tokens += [0] * pad_len
        pad_masks = [1] * len(input_sequence) + [0] * pad_len
        segment_ids = [0] * max_len
        
        all_tokens.append(tokens)
        all_masks.append(pad_masks)
        all_segments.append(segment_ids)
    
    return np.array(all_tokens), np.array(all_masks), np.array(all_segments)

In [17]:
bert_encode(data.contexts, tokenizer, max_len=512)

(array([[  101,  2429,  2000, ...,     0,     0,     0],
        [  101, 21416, 17699, ...,     0,     0,     0],
        [  101,  1996,  2248, ...,     0,     0,     0],
        ...,
        [  101,  4082,  5618, ...,     0,     0,     0],
        [  101,  5658,  4341, ...,     0,     0,     0],
        [  101,  4341,  1999, ...,     0,     0,     0]]),
 array([[1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        ...,
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0],
        [1, 1, 1, ..., 0, 0, 0]]),
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]]))

In [18]:
def build_model(bert_layer, max_len=512):
    input_word_ids = Input(shape=(max_len,), dtype=tf.int32, name="input_word_ids")
    input_mask = Input(shape=(max_len,), dtype=tf.int32, name="input_mask")
    segment_ids = Input(shape=(max_len,), dtype=tf.int32, name="segment_ids")

    _, sequence_output = bert_layer([input_word_ids, input_mask, segment_ids])
    clf_output = sequence_output[:, 0, :]
    
    #if Dropout_num == 0:
        # Without Dropout
    out = Dense(1, activation='sigmoid')(clf_output)
    #else:
        # With Dropout(Dropout_num), Dropout_num > 0
        #x = Dropout(Dropout_num)(clf_output)
        #out = Dense(1, activation='sigmoid')(x)

    model = Model(inputs=[input_word_ids, input_mask, segment_ids], outputs=out)
    model.compile(loss='binary_crossentropy', metrics=['accuracy'])
    
    return model

In [18]:
def build_model(bert_layer, max_len=512):
    input_word_ids = Input(shape=(max_len,), dtype=tf.int32, name="input_word_ids")
    input_mask = Input(shape=(max_len,), dtype=tf.int32, name="input_mask")
    segment_ids = Input(shape=(max_len,), dtype=tf.int32, name="segment_ids")

    _, sequence_output = bert_layer([input_word_ids, input_mask, segment_ids])
    clf_output = sequence_output[:, 0, :]
    out = Dense(1, activation='sigmoid')(clf_output)
    
    model = Model(inputs=[input_word_ids, input_mask, segment_ids], outputs=out)
    model.compile(Adam(lr=1e-5), loss='binary_crossentropy', metrics=['accuracy'])
    
    return model

In [19]:
# Load BERT from the Tensorflow Hub
module_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-24_H-1024_A-16/2"
bert_layer = hub.KerasLayer(module_url, trainable=True)

INFO:absl:Using /tmp/tfhub_modules to cache modules.


In [20]:
X, y = data.contexts, data.labels
X=X.to_list()
y=y.to_list()
X_train, X_dev, y_train, y_dev = train_test_split(X, y, test_size=0.2)

In [21]:
train_input = bert_encode(X_train, tokenizer, max_len=512)
test_input = bert_encode(X_dev, tokenizer, max_len=512)
train_labels = np.array(y_train)

In [25]:
# Build BERT model with my tuning
model_BERT = build_model(bert_layer, max_len=512)
model_BERT.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_word_ids (InputLayer)     [(None, 512)]        0                                            
__________________________________________________________________________________________________
input_mask (InputLayer)         [(None, 512)]        0                                            
__________________________________________________________________________________________________
segment_ids (InputLayer)        [(None, 512)]        0                                            
__________________________________________________________________________________________________
keras_layer (KerasLayer)        [(None, 1024), (None 335141889   input_word_ids[0][0]             
                                                                 input_mask[0][0]           

In [28]:
checkpoint = ModelCheckpoint('model_BERT.h5', monitor='val_loss', save_best_only=True)


train_history = model_BERT.fit(
    train_input, train_labels)
    #validation_split = 0.2,
   # epochs = 3 # recomended 3-5 epochs
    #callbacks= [checkpoint],
    #batch_size = 16,
#)

Train on 3876 samples
  32/3876 [..............................] - ETA: 45:34:04

NotFoundError:  [_Derived_]No gradient defined for op: StatefulPartitionedCall
	 [[{{node Func/_4}}]]
	 [[PartitionedCall/gradients/StatefulPartitionedCall_grad/PartitionedCall/gradients/StatefulPartitionedCall_grad/SymbolicGradient]] [Op:__inference_distributed_function_54858]

Function call stack:
distributed_function
